vcf2hap.o: vcf2hap.c ../local/include/biolibc/vcf.h \
  ../local/include/xtend.h ../local/include/xtend-protos.h \
  ../local/include/biolibc/sam.h ../local/include/biolibc/biolibc.h \
  vcf2hap.h vcf2hap-protos.h
	${CC} -c ${CFLAGS} vcf2hap.c

