vcf2hap.o: vcf2hap.c ../local/include/vcfio.h \
  ../local/include/vcfio-protos.h ../local/include/tsvio.h \
  ../local/include/tsvio-protos.h vcf2hap.h vcf2hap-protos.h
	${CC} -c ${CFLAGS} vcf2hap.c

